name: audio_transformer
version: 0.0.1
author: Oliver Sand <oliver.sand@tentaclelabs.com>
description: A Pub tranformer for converting audio files using FFmpeg.
homepage: https://github.com/Fox32/audio_transformer
documentation: https://github.com/Fox32/audio_transformer
dependencies:
  barback: any
  path: any
